.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "tbf2c" "" "May 2021" ""
.SH "krzysckh"
.nf
tbf2c \- tiny brainfuck to c translator
.fi
.SH "Synopsis"
.nf
tbf2c [filename]
tbf2c [filename\.bf] > [filename\.c]
.fi
.SH "Copyright"
.nf
under WTFPL license\.
.fi
.SH "Options"
.nf
none\.
.fi

